### ISSUE TITLE
Archiver should lock the target table to prevent range lock contention

### ISSUE THREAD

**Issue by joolean** [HearthSim/hsredshift#150]
Even though it's a single, transactional statement, the `DELETE` executed as part of archiving seems to conflict with the transactions run by the ETL process, as observed here:

```
14:46:20 Traceback (most recent call last):
14:46:20   File "scripts/archiver.py", line 111, in <module>
14:46:20     heartbeat=not args.no_heartbeat
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/hsredshift/archiving/archiver.py", line 32, in archive
14:46:20     write_metrics=heartbeat
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/hsredshift/archiving/tables.py", line 299, in archive
14:46:20     archiver.exec_full_archive(execute=execute)
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/hsredshift/archiving/partitions.py", line 108, in exec_full_archive
14:46:20     self._delete(execute=execute)
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/hsredshift/archiving/partitions.py", line 203, in _delete
14:46:20     self.connection.execute(delete_stmt)
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/build/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 942, in execute
14:46:20     return self._execute_text(object, multiparams, params)
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/build/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
14:46:20     statement, parameters
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/build/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
14:46:20     context)
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/build/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
14:46:20     exc_info
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/build/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
14:46:20     reraise(type(exception), exception, tb=exc_tb, cause=cause)
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/build/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
14:46:20     raise value.with_traceback(tb)
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/build/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
14:46:20     context)
14:46:20   File "/var/lib/jenkins/workspace/Archive-Redshift-Tables/build/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
14:46:20     cursor.execute(statement, parameters)
14:46:20 sqlalchemy.exc.InternalError: (psycopg2.InternalError) 1023
14:46:20 DETAIL:  Serializable isolation violation on table - 286740, transactions forming the cycle are: 158947211, 158953624 (pid:6763)
14:46:20  [SQL: "\n\t\tDELETE\n\t\tFROM tag_change\n\t\tWHERE game_date BETWEEN '2018-03-01' AND '2018-03-31'\n\t"] (Background on this error at: http://sqlalche.me/e/2j85)
```

This could be because one or both sides of the conflict are acquiring overlapping range locks on the table, despite targeting entirely different regions of data. To prevent conflicts, let's increase the scope of the locking done by the archiver to have it lock the entire target table for the duration of the `DELETE`.

**Comment by beheh** [comment]
This was done in JIRA.
